---
title: "Dplyr lab"
author: "Kylian Santos"
format: 
  html : default
  pdf : default
editor: visual
knitr:
  opts_chunk:
    echo: FALSE
    message: FALSE
---

```{r configuration}
here::i_am("Dplyr-lab.Rproj")

library(here)
library(ggplot2)
library(dplyr)
library(knitr)
library(tidyr)

spotify <- readRDS("top-spotify-hits-2000-2019.Rds")
dropout <- readRDS("dropout.Rds")

theme_set(theme_bw())
```

## Exercise 1 

### Question 1 

```{r}
nb_song_name <- spotify |> distinct(song) |> nrow()

nb_song <- spotify |> distinct(artist, song) |> nrow()

nb_artist <- spotify |> distinct(artist) |> nrow()

nb_genre <- spotify |> distinct(genre) |> nrow()

cat("There are in this database:", nb_song_name, "different song names,\n")
cat("but there are in reality:", nb_song, "different songs, made by", nb_artist, "different artists.\n")
cat("Moreover, there are:", nb_genre, "different genres in this Spotify database.\n")
```
### Question 2 

```{r}
nb_artist_per_year <- spotify |>
  group_by(year) |>
  distinct(artist) |>
  summarize(artist_count = n())

kable(nb_artist_per_year, caption = "Distinct Artists per Year")
```

### Question 3 

```{r}
most_popular_artist <- spotify |>
  group_by(artist) |>
  summarize(number_of_songs = n_distinct(song)) |>
  slice_max(order_by = number_of_songs)

cat("The most popular artist in the dataset is", most_popular_artist$artist, "with", most_popular_artist$number_of_songs, "songs.")
```

### Question 4 

```{r}
genre_summary <- spotify |>
  group_by(genre) |>
  #distinct(artist, song, .keep_all = TRUE) %>%
  summarize(
    min_tempo = min(tempo, na.rm = TRUE),
    max_tempo = max(tempo, na.rm = TRUE),
    mean_tempo = mean(tempo, na.rm = TRUE),
    median_tempo = median(tempo, na.rm = TRUE),
    num_songs = n_distinct(artist, song)
  )

kable(genre_summary, caption = "Summary of Tempo by Genre")
```

### Question 5 

```{r}
mean_livness_and_danceability_by_year <- spotify |>
  group_by(year) |>
  summarize(mean_livness = mean(liveness, na.rm = TRUE),
            mean_danceability = mean(danceability, na.rm = TRUE))
  
kable(mean_livness_and_danceability_by_year, caption = "Mean of livness and danceability by genre.")
```


### Question 6 

```{r}
mean_livness_and_danceability_by_year |>
  pivot_longer(-year, names_to = "liveness_and_danceability", values_to = "mean") |>
ggplot(aes(x=year, y=mean, color= liveness_and_danceability)) +
  geom_line(lwd = 1.5)
```


## Exercise 2 

### Question 1 

```{r}
median_admision_grade_by_target_and_marital_status <- dropout |>
  group_by(Target,`Marital status`) |>
  summarize(conditioned_median = median(`Admission grade`), .groups = 'drop')
```

### Question 2 

```{r}
table_target_marital <- median_admision_grade_by_target_and_marital_status |>
  pivot_wider(names_from = Target, values_from = conditioned_median)

kable(table_target_marital, caption = "Admission grade median conditioned both on the Target vraiable and on the Marital status")
```

### Question  3

```{r}
media_curricular_by_gender <- dropout |>
  pivot_longer(
    cols = starts_with("Curricular units"),
    names_to = "Curricular",
    values_to = "Value") |>
  group_by(Gender, Curricular) |>
  summarize(conditioned_median = median(Value), .groups = 'drop')
```

### Question 4 

```{r}
table_gender_curricular <- media_curricular_by_gender |>
  pivot_wider(names_from = Gender, values_from = conditioned_median)

kable(table_gender_curricular, caption = "Curricular variable median conditioned on the Genders")
```


